#!/usr/bin/env python3
"""Inline every local \input{} into one self-contained .tex file.

Overleaf and some submission portals accept only a single file. This produces
that file from the modular sources, so the two can never drift: the standalone
copies are generated, never hand-edited.

Only files that exist in the project are inlined. \input{glyphtounicode} refers
to a TeX distribution file and is deliberately left alone.
"""
import pathlib, re, sys

INPUT_RE = re.compile(r'^([ \t]*)\\input\{([^}]+)\}[ \t]*$', re.M)

def resolve(name, root):
    for cand in (root / name, root / f"{name}.tex"):
        if cand.is_file():
            return cand
    return None

def flatten(path, root, seen=None):
    seen = seen or set()
    path = path.resolve()
    if path in seen:
        raise RuntimeError(f"circular \\input at {path}")
    seen = seen | {path}

    def repl(m):
        indent, name = m.group(1), m.group(2)
        target = resolve(name, root)
        if target is None:
            return m.group(0)          # a TeX system file; leave it
        body = flatten(target, root, seen).rstrip('\n')
        rel = target.relative_to(root)
        return (f"{indent}% >>> inlined from {rel} "
                f"(generated by tools/flatten.py; edit the original)\n"
                f"{body}\n"
                f"{indent}% <<< end {rel}")

    return INPUT_RE.sub(repl, path.read_text())

if __name__ == "__main__":
    root = pathlib.Path.cwd()
    out_dir = root / "dist"
    out_dir.mkdir(exist_ok=True)
    for src in sys.argv[1:]:
        src_path = pathlib.Path(src)
        out = out_dir / f"{src_path.stem}-standalone.tex"
        text = flatten(src_path, root)
        header = ("% GENERATED FILE - do not edit.\n"
                  f"% Built from {src} by tools/flatten.py; run `make standalone`.\n"
                  "% Self-contained: upload this one file to Overleaf and compile.\n")
        out.write_text(header + text)
        remaining = len(INPUT_RE.findall(text))
        print(f"  {out}  ({len(text.splitlines())} lines, "
              f"{remaining} un-inlined \\input left: expected 1 for glyphtounicode)")
